# Generated by Django 4.2 on 2025-04-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_remove_user_email_verified_at_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
