# Generated by Django 4.2 on 2025-04-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
