version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_web
    volumes:
      - ../django_project:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    command: ["gunicorn", "--config", "/docker/gunicorn/gunicorn.conf.py", "django_project.wsgi:application"]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    container_name: django_nginx
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"

volumes:
  pg_data:
